# Generated by Django 6.0.2 on 2026-05-02 16:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_remove_elementopage_block_id_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementopage',
            name='block_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productopage',
            name='elementos',
            field=wagtail.fields.StreamField([('elemento', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('imagen', 0), ('alt_imagen', 1), ('titulo', 1), ('block_id', 2)]], {'group': 'Galería'})}, help_text='Agregue imágenes a la galería del producto.'),
        ),
        migrations.AlterField(
            model_name='elementopage',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
