# Generated by Django 6.0.2 on 2026-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_elementopage_block_id_productopage_elementos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopage',
            name='unidad',
            field=models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('m', 'm'), ('px', 'px')], default='cm', max_length=10, verbose_name='Unidad de medida'),
        ),
    ]
