# Generated by Django 6.0.2 on 2026-07-17 20:48

from django.db import migrations, models


def migrate_dimensions_to_description(apps, schema_editor):
    ElementoPage = apps.get_model('produccion', 'ElementoPage')
    for elemento in ElementoPage.objects.all():
        prefix_parts = []

        if elemento.ancho or elemento.alto or elemento.profundidad:
            dim_parts = []
            if elemento.ancho:
                dim_parts.append(str(elemento.ancho))
            if elemento.alto:
                dim_parts.append(str(elemento.alto))
            if elemento.profundidad:
                dim_parts.append(str(elemento.profundidad))
            if dim_parts:
                dim_str = ' x '.join(dim_parts)
                if elemento.unidad:
                    dim_str = f'{dim_str} {elemento.unidad}'
                prefix_parts.append(dim_str)

        if elemento.peso:
            peso_str = f'Peso {elemento.peso}'
            if elemento.unidad_peso:
                peso_str = f'{peso_str} {elemento.unidad_peso}'
            prefix_parts.append(peso_str)

        if prefix_parts:
            existing = elemento.descripcion or ''
            new_prefix = '\n'.join(prefix_parts) + '\n'
            elemento.descripcion = new_prefix + existing
            elemento.save(update_fields=['descripcion'])

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_elementopage_unidad'),
    ]

    operations = [
        migrations.RunPython(
            migrate_dimensions_to_description,
            reverse_migration
        ),
        migrations.RemoveField(
            model_name='elementopage',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='elementopage',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='elementopage',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='elementopage',
            name='profundidad',
        ),
        migrations.RemoveField(
            model_name='elementopage',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='elementopage',
            name='unidad_peso',
        ),
    ]
