# Generated by Django 6.0.2 on 2026-07-17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('produccion', '0005_remove_elementopage_alto_remove_elementopage_ancho_and_more'),
    ]

    operations = [
        # Eliminar columna 'videos' residual de produccion_productopage
        migrations.RunSQL(
            sql='ALTER TABLE produccion_productopage DROP COLUMN videos',
            reverse_sql='ALTER TABLE produccion_productopage ADD COLUMN videos TEXT NOT NULL DEFAULT \'[]\'',
        ),

        # Eliminar tabla huérfana produccion_elementovideopage
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS produccion_elementovideopage',
            reverse_sql='',
        ),
    ]
