# Generated by Django 6.0.2 on 2026-07-17
# Modificada por hernando_tejedor en 2026-08-15
# (con ayuda de OpenCode+MiniMax M3)

from django.db import migrations


def drop_videos_if_exists(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info('produccion_productopage')")
        cols = {row[1] for row in cursor.fetchall()}
        if 'videos' in cols:
            cursor.execute("ALTER TABLE produccion_productopage DROP COLUMN videos")


def drop_orphaned_table_if_exists(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='produccion_elementovideopage'"
        )
        if cursor.fetchone():
            cursor.execute("DROP TABLE produccion_elementovideopage")


class Migration(migrations.Migration):
    dependencies = [
        ('produccion', '0005_remove_elementopage_alto_remove_elementopage_ancho_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_videos_if_exists, migrations.RunPython.noop),
        migrations.RunPython(drop_orphaned_table_if_exists, migrations.RunPython.noop),
    ]
