# Generated by Django 6.0.2 on 2026-07-22 21:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_remove_orphaned_db_tables_and_fields'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementopage',
            name='alt_imagen',
        ),
        migrations.RemoveField(
            model_name='elementopage',
            name='imagen',
        ),
        migrations.AddField(
            model_name='elementopage',
            name='alt_thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt imagen'),
        ),
        migrations.AddField(
            model_name='elementopage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='elementopage',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('texto', 'Texto')], default='imagen', max_length=10),
        ),
        migrations.AlterField(
            model_name='productopage',
            name='elementos',
            field=wagtail.fields.StreamField([('elemento', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('thumbnail', 0), ('alt_thumbnail', 1), ('titulo', 1), ('block_id', 2)]], {'group': 'Galería'})}, help_text='Agregue imágenes a la galería del producto.'),
        ),
    ]
