# Generated by Django 6.0.2 on 2026-07-22 21:54
# Modificada por hernando_tejedor en 2026-08-15
# (con ayuda de OpenCode+MiniMax M3)
import json

import django.db.models.deletion
from django.db import migrations, models


def rename_imagen_columns(apps, schema_editor):
    """Renombra imagen_id -> thumbnail_id y alt_imagen -> alt_thumbnail si no se hizo."""
    with schema_editor.connection.cursor() as cursor:
        # Verificar estado actual de columnas
        cursor.execute("PRAGMA table_info('produccion_elementopage')")
        cols = {row[1] for row in cursor.fetchall()}

        # Caso 1: existen las dos viejas, no existen las nuevas
        if 'imagen_id' in cols and 'thumbnail_id' not in cols:
            cursor.execute(
                "ALTER TABLE produccion_elementopage "
                "RENAME COLUMN imagen_id TO thumbnail_id"
            )
        if 'alt_imagen' in cols and 'alt_thumbnail' not in cols:
            cursor.execute(
                "ALTER TABLE produccion_elementopage "
                "RENAME COLUMN alt_imagen TO alt_thumbnail"
            )


def add_tipo(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info('produccion_elementopage')")
        cols = {row[1] for row in cursor.fetchall()}
        if 'tipo' not in cols:
            cursor.execute(
                "ALTER TABLE produccion_elementopage "
                "ADD COLUMN tipo varchar(10) DEFAULT 'imagen' NOT NULL"
            )


def transform_productos_json(apps, schema_editor):
    """ Transforma el JSON de produccion_productopage.elementos:
        'imagen' -> 'thumbnail', 'alt_imagen' -> 'alt_thumbnail'.
        Preserva todos los demás campos.
        Usa sqlite3 nativo en vez de CursorDebugWrapper para evitar bug
        de Django 6.0.2 + Python 3.14 en last_executed_query (formatea 'sql'
        con '=' usando %-formatting)."""
    raw_connection =schema_editor.connection.connection
    cursor = raw_connection.cursor()
    # with schema_editor.connection.cursor() as cursor:
    try:
        cursor.execute(
            "SELECT page_ptr_id, elementos FROM produccion_productopage "
            "WHERE elementos IS NOT NULL"
        )
        updates = []
        for pid, elementos_json in cursor.fetchall():
            try:
                data = json.loads(elementos_json)
            except (json.JSONDecodeError, TypeError):
                continue
            changed = False
            for block in data:
                if block.get('type') != 'elemento':
                    continue
                value = block.get('value', {})
                if 'imagen' in value:
                    value['thumbnail'] = value.pop('imagen')
                    changed = True
                if 'alt_imagen' in value:
                    value['alt_thumbnail'] = value.pop('alt_imagen')
                    changed = True
            if changed:
                updates.append((json.dumps(data, ensure_ascii=False), pid))

        for new_json, pid in updates:
            cursor.execute(
                "UPDATE produccion_productopage SET elementos=? WHERE page_ptr_id=?",
                (new_json, pid)
            )
        raw_connection.commit()
    finally:
        cursor.close()


def reverse_noop(apps, schema_editor):
    pass


_state_operations = [
    migrations.RemoveField(
        model_name='elementopage',
        name='alt_imagen',
    ),
    migrations.RemoveField(
        model_name='elementopage',
        name='imagen',
    ),
    migrations.AddField(
        model_name='elementopage',
        name='alt_thumbnail',
        field=models.CharField(
            blank=True, max_length=255, null=True, verbose_name="alt imagen",
        ),
    ),
    migrations.AddField(
        model_name='elementopage',
        name='thumbnail',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='+', to='wagtailimages.image',
            verbose_name='imagen',
        ),
    ),
    migrations.AddField(
        model_name='elementopage',
        name='tipo',
        field=models.CharField(
            choices=[
                ('imagen', 'Imagen'), ('video', 'Video'),
                ('audio', 'Audio'), ('texto', 'Texto'),
            ],
            default='imagen', max_length=10,
        ),
    ),
]

_database_operations = [
    migrations.RunPython(rename_imagen_columns, reverse_noop),
    migrations.RunPython(add_tipo, reverse_noop),
    migrations.RunPython(transform_productos_json, reverse_noop),
]

class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_remove_orphaned_db_tables_and_fields'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=_state_operations,
            database_operations=_database_operations,
        ),
    ]

