# Generated by Django 6.0.2 on 2026-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_remove_elementopage_alt_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementopage',
            name='contenido_texto',
            field=models.TextField(blank=True),
        ),
    ]
