# Generated by Django 6.0.2 on 2026-07-25 13:46
# Modificada por hernando_tejedor en 2026-08-15
# (con ayuda de OpenCode+MiniMax M3)
from django.db import migrations, models


def add_contenido_texto(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info('produccion_elementopage')")
        cols = {row[1] for row in cursor.fetchall()}
        if 'contenido_texto' not in cols:
            cursor.execute(
                "ALTER TABLE produccion_elementopage "
                "ADD COLUMN contenido_texto TEXT DEFAULT '' NOT NULL"
            )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_remove_elementopage_alt_imagen_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='elementopage',
                    name='contenido_texto',
                    field=models.TextField(blank=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_contenido_texto, reverse_noop),
            ],
        ),
    ]

