# Generated by Django 6.0.2 on 2026-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_elementopage_contenido_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementopage',
            name='contenido_url',
            field=models.URLField(blank=True),
        ),
    ]
