# Generated by Django 6.0.2 on 2026-07-25 13:50
# Modificada por hernando_tejedor en 2026-08-15
# (con ayuda de OpenCode+MiniMax M3)
from django.db import migrations, models


def add_contenido_url(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info('produccion_elementopage')")
        cols = {row[1] for row in cursor.fetchall()}
        if 'contenido_url' not in cols:
            cursor.execute(
                "ALTER TABLE produccion_elementopage "
                "ADD COLUMN contenido_url varchar(200) DEFAULT '' NOT NULL"
            )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_elementopage_contenido_texto'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='elementopage',
                    name='contenido_url',
                    field=models.URLField(blank=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_contenido_url, reverse_noop),
            ],
        ),
    ]
