# Generated by Django 6.0.2 on 2026-07-30 22:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_elementopage_contenido_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopage',
            name='elementos',
            field=wagtail.fields.StreamField([('elemento', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('texto', 'Texto')], 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('thumbnail', 0), ('alt_thumbnail', 1), ('tipo', 2), ('contenido_url', 3), ('contenido_texto', 4), ('titulo', 1), ('block_id', 5)]], {'group': 'Galería'})}, help_text='Agregue imágenes a la galería del producto.'),
        ),
    ]
