# Generated by Django 6.0.2 on 2026-08-31 23:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_productopage_elementos'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementopage',
            name='contenido_multimedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='archivo multimedia'),
        ),
        migrations.AlterField(
            model_name='productopage',
            name='elementos',
            field=wagtail.fields.StreamField([('elemento', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('texto', 'Texto')], 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('thumbnail', 0), ('alt_thumbnail', 1), ('tipo', 2), ('contenido_url', 3), ('contenido_multimedia', 4), ('contenido_texto', 5), ('titulo', 1), ('block_id', 6)]], {'group': 'Galería'})}, help_text='Agregue imágenes a la galería del producto.'),
        ),
    ]
