# Generated by Django 6.0.2 on 2026-03-27 21:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('entradas', wagtail.fields.StreamField([('entrada', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Año', 'max_length': 4}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Lugar / Institución', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Otros datos', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('anio', 0), ('titulo', 1), ('lugar', 2), ('nota', 3)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
