# Generated by Django 6.0.2 on 2026-04-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_contactpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='to_address',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
