# Generated by Django 6.0.2 on 2026-06-09 21:12

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_contactpage_to_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumpage',
            name='entradas',
            field=wagtail.fields.StreamField([('entrada', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Año', 'max_length': 4, 'validators': [django.core.validators.RegexValidator(message='El año debe estar entre 1900 y 2099', regex='^(19|20)\\d{2}$')]}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Año hasta', 'max_length': 4, 'required': False, 'validators': [django.core.validators.RegexValidator(message='El año debe estar entre 1900 y 2099', regex='^(19|20)\\d{2}$')]}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 255}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Lugar / Institución', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Otros datos', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('anio', 0), ('anio_hasta', 1), ('titulo', 2), ('lugar', 3), ('nota', 4)]], {})}, verbose_name='Entradas'),
        ),
    ]
