# Generated by Django 6.0.2 on 2026-03-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_footertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=255, verbose_name='Título del sitio')),
            ],
            options={
                'verbose_name': 'configuración general',
            },
        ),
        migrations.AlterModelOptions(
            name='navigationsettings',
            options={'verbose_name': 'configuración de redes sociales'},
        ),
    ]
