# Generated by Django 6.0.2 on 2026-03-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_generalsettings_alter_navigationsettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
            ],
            options={
                'verbose_name': 'configuración de contacto',
            },
        ),
    ]
