# Generated by Django 6.0.2 on 2026-03-28 17:06

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_curriculumpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumpage',
            options={'verbose_name': 'Página de currículum'},
        ),
        migrations.AlterField(
            model_name='curriculumpage',
            name='entradas',
            field=wagtail.fields.StreamField([('entrada', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Año', 'max_length': 4, 'validators': [django.core.validators.RegexValidator(message='El año debe tener exactamente cuatro dígitos', regex='^\\d{4}$')]}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Lugar / Institución', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Otros datos', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('anio', 0), ('titulo', 1), ('lugar', 2), ('nota', 3)]], {})}, verbose_name='Entradas'),
        ),
    ]
