# Generated by Django 6.0.2 on 2026-03-30 13:21

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_curriculumpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumpage',
            name='entradas',
            field=wagtail.fields.StreamField([('entrada', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Año', 'max_length': 4, 'validators': [django.core.validators.RegexValidator(message='El año debe estar entre 1900 y 2099', regex='^(19|20)\\d{2}$')]}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Lugar / Institución', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Otros datos', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('anio', 0), ('titulo', 1), ('lugar', 2), ('nota', 3)]], {})}, verbose_name='Entradas'),
        ),
    ]
