# Generated by Django 6.0.2 on 2026-04-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_remove_contactpage_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='to_address',
            field=models.EmailField(blank=True, help_text='Si se deja vacío se usará la dirección de ContactSettings', max_length=254, verbose_name='Dirección de destino'),
        ),
    ]
