# Generated by Django 6.0.2 on 2026-02-13 23:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('franja', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('imagen', 0), ('url', 1)]], {'group': 'Section'})}, help_text='Agregue una imagen y una URL para cada sección que quiera que aparezca en la portada'),
        ),
    ]
