# Generated by Django 6.0.2 on 2026-02-14 22:03

import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('franja', 10)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 6: ('wagtail.blocks.EmailBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('link_to', 1), ('page', 2), ('file', 3), ('custom_url', 4), ('anchor', 5), ('email', 6), ('phone', 7), ('new_window', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('imagen', 0), ('url', 9)]], {'group': 'Section'})}, help_text='Agregue una imagen y una URL para cada sección que quiera que aparezca en la portada'),
        ),
    ]
