# Generated by Django 6.0.2 on 2026-04-21 23:27

import django.db.models.deletion
import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', wagtail.fields.RichTextField(blank=True)),
                ('productos', wagtail.fields.StreamField([('producto', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 7: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 8: ('wagtail.blocks.EmailBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('link_to', 3), ('page', 4), ('file', 5), ('custom_url', 6), ('anchor', 7), ('email', 8), ('phone', 9), ('new_window', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('nombre', 0), ('descripcion', 1), ('imagen', 2), ('link', 11)]], {'group': 'Section'})}, help_text='Agregue una imagen, un nombre y un enlace.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', wagtail.fields.RichTextField(blank=True)),
                ('elementos', wagtail.fields.StreamField([('elemento', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('imagen', 0), ('alt_imagen', 1), ('titulo', 1), ('block_id', 2)]], {'group': 'Galería'})}, help_text='Agregue imágenes a la galería del producto.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ElementoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('block_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho')),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profundidad')),
                ('unidad', models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('m', 'm')], default='cm', max_length=10, verbose_name='Unidad de medida')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso')),
                ('unidad_peso', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg')], default='kg', max_length=10, verbose_name='Unidad de peso')),
                ('descripcion', wagtail.fields.RichTextField(blank=True)),
                ('comentarios', wagtail.fields.StreamField([('comentario', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
