# Generated by Django 6.0.2 on 2026-04-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementopage',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='productopage',
            name='elementos',
        ),
        migrations.AlterField(
            model_name='elementopage',
            name='imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
