# Generated by Django 6.0.2 on 2026-02-15 22:51

import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_productopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopage',
            name='imagenes',
            field=wagtail.fields.StreamField([('imagen', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 7: ('wagtail.blocks.EmailBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('link_to', 2), ('page', 3), ('file', 4), ('custom_url', 5), ('anchor', 6), ('email', 7), ('phone', 8), ('new_window', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('nombre', 0), ('imagen', 1), ('link', 10)]], {'group': 'Section'})}, help_text='Agregue una imagen y opcionalmente un nombre'),
        ),
    ]
