# Generated by Django 6.0.2 on 2026-03-20 12:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def crear_elemento_pages(apps, schema_editor):
    print("Creando páginas elemento.......")
    from produccion.models import ElementoPage, ProductoPage

    for producto in ProductoPage.objects.all():

        for i, bloque in enumerate(producto.imagenes):
            if bloque.block_type != "imagen":
                continue

            valor = bloque.value
            nombre = valor.get("nombre") or ""
            imagen_struct = valor.get("imagen")

            elemento = ElementoPage(
                title=nombre or f"Elemento {i + 1}",
                titulo=nombre,
                slug=f"elemento-{i + 1}",
            )

            if imagen_struct:
                elemento.imagen = imagen_struct
                elemento.alt_imagen = nombre or ""

            producto.add_child(instance=elemento)


def eliminar_elemento_pages(apps, schema_editor):
    print("Eliminando páginas elemento.......")
    from produccion.models import ElementoPage
    ElementoPage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_productopage_imagenes'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('alt_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho')),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profundidad')),
                ('unidad', models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('m', 'm')], max_length=10, null=True, verbose_name='Unidad de medida')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profundidad')),
                ('unidad_peso', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg')], max_length=10, null=True, verbose_name='Unidad de peso')),
                ('descripcion', wagtail.fields.RichTextField(blank=True)),
                ('comentarios', wagtail.fields.StreamField([('comentario', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RunPython(crear_elemento_pages, eliminar_elemento_pages),
    ]
