# Generated by Django 6.0.2 on 2026-03-20 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_elementopage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopage',
            name='imagenes',
        ),
        migrations.AlterField(
            model_name='elementopage',
            name='imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='elementopage',
            name='unidad',
            field=models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('m', 'm')], default='cm', max_length=10, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='elementopage',
            name='unidad_peso',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg')], default='kg', max_length=10, verbose_name='Unidad de peso'),
        ),
    ]
