# Generated by Django 6.0.2 on 2026-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_remove_productopage_imagenes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopage',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso'),
        ),
    ]
